apiVersion: v1
kind: Pod
metadata:
  name: rdma-demo
  namespace: default
spec:
  nodeName: master-node
  containers:
  - name: rdma-demo-001
    command: [ "/bin/bash", "-c", "--", "trap : TERM INT; sleep infinity & wait" ]
    image: ir0cn/rdma-demo
    imagePullPolicy: IfNotPresent
    #ports:
    #- containerPort: 90