---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    app: redis
    role: master

---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    app: redis
    role: slave

---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  labels:
    app: redis
spec:
  ports:
    - port: 26379
      name: sentinel
  selector:
    app: redis
    role: sentinel