---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-scripts
data:
  init.sh: |-
    set -ex

    {{if gt .Values.replicas 0 }}
    [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
    PET_ORDINAL=${BASH_REMATCH[1]}
    if [ "$PET_ORDINAL" = "0" ]; then
      PET_ORDINAL={{.Values.replicas}}
    fi
    slaveOf=redis-$(($PET_ORDINAL-1)).redis-headless
    redis-server /conf/redis.conf --slaveof=$slaveOf:6379 --replicaOf=$slaveOf:6379 --requirepass {{.Values.password}}

    {{else}}
    redis-server /conf/redis.conf --requirepass {{.Values.password}}
    {{end}}
