apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      {{- include "podAntiAffinity.tpl" . }}
      {{- include "nodeSelector.tpl" . }}
      containers:
        - name: redis
        {{ include "redis.tpl" . }}
      {{ include "allvulumes.tpl" . }}
  {{ include "pvc.tpl" .}}
