apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-apiserver
  template:
    metadata:
      labels:
        app: kube-apiserver
    spec:
      containers:
      - image: ir0cn/kube-apiserver:latest
        imagePullPolicy: IfNotPresent
        name: kube-apiserver
        ports:
        - containerPort: 6443
        env:
        - name: PORT
          value: "6443"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - port: 6443
      targetPort: 6443
      protocol: TCP
  type: NodePort
  selector:
    app: kube-apiserver