apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-echoserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udp-echoserver
  template:
    metadata:
      labels:
        app: udp-echoserver
    spec:
      containers:
      - image: ir0cn/udpecho:arm64
        imagePullPolicy: IfNotPresent
        name: udp-echoserver
        ports:
        - containerPort: 33333
---
apiVersion: v1
kind: Service
metadata:
  name: udp-echoserver
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - port: 33333
      targetPort: 33333
      protocol: UDP
  type: ClusterIP
  selector:
    app: udp-echoserver

