apiVersion: v1
kind: ConfigMap
metadata:
  name: init-nginx-scripts
data:
  init.sh: |-
    #!/bin/bash
    set -e -x
    mkdir -p /usr/share/nginx/html/
    dd if=/dev/zero of=/usr/share/nginx/html/20.html bs=20 count=1
    dd if=/dev/zero of=/usr/share/nginx/html/300.html bs=300 count=1
    dd if=/dev/zero of=/usr/share/nginx/html/1024.html bs=1024 count=1
    dd if=/dev/zero of=/usr/share/nginx/html/10240.html bs=1024 count=10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-config
data:
  nginx.conf: |-
    user nginx;
    worker_processes 8;
    error_log /dev/null;
    pid /var/run/nginx.pid;

    events {
      worker_connections 102400;
    }

    http {
      access_log off;
      sendfile on;
      keepalive_timeout 65;
      gzip off;
      server {
        listen 80;
        listen [::]:90;
        server_name localhost;

        location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
        }
      }    
    }


---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx:1.25.0-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: 200Mi
        volumeMounts:
          - name: nginx-data
            mountPath: /usr/share/nginx/html
          - name: default-conf
            mountPath: /etc/nginx
      initContainers:
      - name: init-nginx
        image: busybox
        imagePullPolicy: IfNotPresent
        command: 
          - sh 
          - /var/run/scripts/init.sh
        volumeMounts:
          - name: nginx-data
            mountPath: /usr/share/nginx/html
          - name: init-scripts
            mountPath: /var/run/scripts
      volumes:
      - name: nginx-data
        emptyDir: {}
      - name: default-conf
        configMap:
          name: nginx-default-config
      - name: init-scripts
        configMap:
          name: init-nginx-scripts
