apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-slave
spec:
  selector:
    matchLabels:
      app: mysql
      role: slave
  serviceName: mysql-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        role: slave
    spec:
      initContainers:
      - name: init-mysql
        {{ include "initmysql.tpl" . }}
      - name: clone-mysql
        {{ include "clonemysql.tpl" . }}
      containers:
      - name: mysql
        {{ include "mysql.tpl" . }}
      - name: xtrabackup
        {{ include "xtrabackup.tpl" . }}
      {{ include "allvulumes.tpl" . }}
  {{ include "pvc.tpl" .}}
