apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
spec:
  selector:
    matchLabels:
      app: mysql
      role: master
  serviceName: mysql-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        role: master
    spec:
      {{- include "podAntiAffinity.tpl" . }}
      {{- include "nodeSelector.tpl" . }}
      initContainers:
      - name: init-mysql
        {{ include "initmysql.tpl" . }}
      containers:
      - name: mysql
        {{ include "mysql.tpl" . }}
      - name: xtrabackup
        {{ include "xtrabackup.tpl" . }}
      {{ include "allvulumes.tpl" . }}
  {{ include "pvc.tpl" .}}
