mysql:
  image: mysql:5.7.22
  xtrabackupImage: xtrabackup:2.4.29-amd64-2
  slaveReplicas: 2      # 从库的数量
  username: chogori
  password:
  rootPassword:
  storageSize: 10Gi     # PVC的容量
  storageClassName:     # StorageClass的名称，不填则需要有默认SC

redis:
  image: redis:5.0.14
  slaveReplicas: 2      # 从库的数量
  password:
  sentinel: false       # 是否启用哨兵模式
  storageSize: 10Gi     # PVC的容量
  storageClassName:     # StorageClass的名称，不填则需要有默认SC

etcd:
  image: bitnami/etcd:3.5.14
  replicas: 3           # 副本数量
  password:
  storageSize: 10Gi     # PVC的容量
  storageClassName:     # StorageClass的名称，不填则需要有默认SC

global:
  nodeSelector: {}      # 节点选择器
  antiAffinity: false   # 节点反亲和
  imagePullSecrets:
    - name: xxhub
