mysql:
  image: mysql:5.7
  xtrabackupImage: gcr.io/google-samples/xtrabackup:1.0
  slaveCount: 0
  username: chogori
  password: 123456

redis:
  image: hub.jdcloud.com/chogori/redis:5.0.14
  password: 123456

global:
  storageSize: 10Gi
  storageClassName: csi-hostpath-fast
  