mysql:
#  image: mysql:5.7
  image: hub.jdcloud.com/chogori/mysql:5.7.22
#  xtrabackupImage: gcr.io/google-samples/xtrabackup:1.0
  xtrabackupImage: hub.jdcloud.com/chogori/xtrabackup:8.0.35-amd64
  slaveReplicas: 2      # 从库的数量
  username: chogori
  password: jwaFQGqcGd5rmf7a
  rootPassword: jwaFQGqcGd5rmf7a

redis:
#  image: redis:5.0.14
  image: hub.jdcloud.com/chogori/redis:5.0.14
  slaveReplicas: 2      # 从库的数量
  password: jwaFQGqcGd5rmf7a
  sentinel: false       # 是否启用哨兵模式

global:
  storageSize: 10Gi     # PVC的容量
  storageClassName:     # StorageClass的名称，不填则需要有默认SC
  nodeSelector: {}      # 节点选择器
  antiAffinity: false   # 节点反亲和
  imagePullSecrets:
    - name: jdosnet-hub
