mysql:
  image: mysql:5.7
  #image: hub.jdcloud.com/chogori/mysql:5.7.22
  xtrabackupImage: gcr.io/google-samples/xtrabackup:1.0
  slaveReplicas: 1      # 从库的数量
  username: chogori
  password: jwaFQGqcGd5rmf7a
  rootPassword: jwaFQGqcGd5rmf7a

redis:
  image: redis:5.0.14
  #image: hub.jdcloud.com/chogori/redis:5.0.14
  replicas: 3
  password: 123456

global:
  storageSize: 10Gi     # PVC的容量
  storageClassName:     # StorageClass的名称，不填则需要有默认SC
  nodeSelector: {}      # 节点选择器
  antiAffinity: false   # 节点反亲和
