mysql:
  image: mysql:5.7
  xtrabackupImage: gcr.io/google-samples/xtrabackup:1.0
  slaveCount: 1
  username: chogori
  password: jwaFQGqcGd5rmf7a
  rootPassword: jwaFQGqcGd5rmf7a

redis:
  image: hub.jdcloud.com/chogori/redis:5.0.14
  password: 123456

global:
  storageSize: 10Gi
  storageClassName: csi-hostpath-fast
  